// frontend/src/views/DatasetManagement.vue
<template>
  <div class="dataset-management">
    <h1 class="text-h4 mb-6">Dataset Management</h1>
    
    <!-- Dataset Upload Section -->
    <section class="mb-8">
      <DatasetUpload @upload-success="handleUploadSuccess" />
    </section>
    
    <!-- Dataset List and Metrics -->
    <section>
      <v-card>
        <v-card-title>
          Datasets
          <v-spacer></v-spacer>
          <v-text-field
            v-model="search"
            append-icon="mdi-magnify"
            label="Search"
            single-line
            hide-details
          ></v-text-field>
        </v-card-title>
        
        <v-data-table
          :headers="headers"
          :items="datasets"
          :search="search"
          :loading="loading"
          class="elevation-1"
        >
          <template v-slot:item.actions="{ item }">
            <v-btn
              color="primary"
              text
              @click="viewMetrics(item)"
            >
              View Metrics
            </v-btn>
          </template>
        </v-data-table>
      </v-card>
    </section>
    
    <!-- Metrics Dialog -->
    <v-dialog
      v-model="metricsDialog"
      fullscreen
      hide-overlay
      transition="dialog-bottom-transition"
    >
      <v-card>
        <v-toolbar dark color="primary">
          <v-btn
            icon
            dark
            @click="metricsDialog = false"
          >
            <v-icon>mdi-close</v-icon>
          </v-btn>
          <v-toolbar-title>Dataset Metrics</v-toolbar-title>
        </v-toolbar>
        
        <v-card-text>
          <MetricsVisualization
            v-if="selectedDataset"
            :dataset-id="selectedDataset.id"
          />
        </v-card-text>
      </v-card>
    </v-dialog>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue'
import DatasetUpload from '../components/DatasetUpload.vue'
import MetricsVisualization from '../components/MetricsVisualization.vue'
import axios from 'axios'

export default defineComponent({
  name: 'DatasetManagement',
  
  components: {
    DatasetUpload,
    MetricsVisualization
  },
  
  setup() {
    const datasets = ref([])
    const loading = ref(false)
    const search = ref('')
    const metricsDialog = ref(false)
    const selectedDataset = ref(null)
    
    const headers = [
      { text: 'Name', value: 'name' },
      { text: 'Description', value: 'description' },
      { text: 'Format', value: 'format' },
      { text: 'Size', value: 'size' },
      { text: 'Created At', value: 'created_at' },
      { text: 'Actions', value: 'actions', sortable: false }
    ]
    
    const fetchDatasets = async () => {
      loading.value = true
      try {
        const response = await axios.get('http://localhost:8000/datasets/')
        datasets.value = response.data
      } catch (error) {
        console.error('Error fetching datasets:', error)
      } finally {
        loading.value = false
      }
    }
    
    const handleUploadSuccess = () => {
      fetchDatasets()
    }
    
    const viewMetrics = (dataset: any) => {
      selectedDataset.value = dataset
      metricsDialog.value = true
    }
    
    onMounted(() => {
      fetchDatasets()
    })
    
    return {
      datasets,
      loading,
      search,
      headers,
      metricsDialog,
      selectedDataset,
      handleUploadSuccess,
      viewMetrics
    }
  }
})
</script>

<style scoped>
.dataset-management {
  padding: 20px;
  max-width: 1400px;
  margin: 0 auto;
}
</style>

// frontend/src/views/DatasetManagement.tsx
import { useState, useEffect } from 'react';
import { 
  Typography, Card, CardContent, TextField, 
  Button, Dialog, AppBar, Toolbar, IconButton, 
  Table, TableBody, TableCell, TableHead, TableRow, TableContainer, Paper
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import DatasetUpload from '../components/DatasetUpload';
import MetricsVisualization from '../components/MetricsVisualization';
import axios from 'axios';

interface Dataset {
  id: string;
  name: string;
  description: string;
  format: string;
  size: string;
  created_at: string;
}

function DatasetManagement() {
  const [datasets, setDatasets] = useState<Dataset[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const [search, setSearch] = useState<string>('');
  const [metricsDialog, setMetricsDialog] = useState<boolean>(false);
  const [selectedDataset, setSelectedDataset] = useState<Dataset | null>(null);

  const fetchDatasets = async () => {
    setLoading(true);
    try {
      const response = await axios.get('http://localhost:8000/datasets/');
      setDatasets(response.data);
    } catch (error) {
      console.error('Error fetching datasets:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleUploadSuccess = () => {
    fetchDatasets();
  };

  const viewMetrics = (dataset: Dataset) => {
    setSelectedDataset(dataset);
    setMetricsDialog(true);
  };

  useEffect(() => {
    fetchDatasets();
  }, []);

  const filteredDatasets = datasets.filter((dataset) => {
    return Object.values(dataset).some((value) => 
      value?.toString().toLowerCase().includes(search.toLowerCase())
    );
  });

  return (
    <div className="dataset-management">
      <Typography variant="h4" sx={{ mb: 6 }}>Dataset Management</Typography>
      
      {/* Dataset Upload Section */}
      <section style={{ marginBottom: '2rem' }}>
        <DatasetUpload onUploadSuccess={handleUploadSuccess} />
      </section>
      
      {/* Dataset List and Metrics */}
      <section>
        <Card>
          <CardContent sx={{ padding: '0 1rem 1rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '1rem 0' }}>
              <Typography variant="h6">Datasets</Typography>
              <TextField
                label="Search"
                variant="outlined"
                size="small"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            
            <TableContainer component={Paper}>
              <Table>
                <TableHead>
                  <TableRow>
                    <TableCell>Name</TableCell>
                    <TableCell>Description</TableCell>
                    <TableCell>Format</TableCell>
                    <TableCell>Size</TableCell>
                    <TableCell>Created At</TableCell>
                    <TableCell>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {loading ? (
                    <TableRow>
                      <TableCell colSpan={6} align="center">Loading...</TableCell>
                    </TableRow>
                  ) : filteredDatasets.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={6} align="center">No datasets found</TableCell>
                    </TableRow>
                  ) : (
                    filteredDatasets.map((dataset) => (
                      <TableRow key={dataset.id}>
                        <TableCell>{dataset.name}</TableCell>
                        <TableCell>{dataset.description}</TableCell>
                        <TableCell>{dataset.format}</TableCell>
                        <TableCell>{dataset.size}</TableCell>
                        <TableCell>{dataset.created_at}</TableCell>
                        <TableCell>
                          <Button
                            color="primary"
                            onClick={() => viewMetrics(dataset)}
                          >
                            View Metrics
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        </Card>
      </section>
      
      {/* Metrics Dialog */}
      <Dialog
        fullScreen
        open={metricsDialog}
        onClose={() => setMetricsDialog(false)}
      >
        <AppBar sx={{ position: 'relative' }}>
          <Toolbar>
            <IconButton
              edge="start"
              color="inherit"
              onClick={() => setMetricsDialog(false)}
              aria-label="close"
            >
              <CloseIcon />
            </IconButton>
            <Typography sx={{ ml: 2, flex: 1 }} variant="h6">
              Dataset Metrics
            </Typography>
          </Toolbar>
        </AppBar>
        <div style={{ padding: '2rem' }}>
          {selectedDataset && (
            <MetricsVisualization datasetId={selectedDataset.id} />
          )}
        </div>
      </Dialog>
    </div>
  );
}

export default DatasetManagement;
